title: <p align=center> Minimal theme </p>
logo: /assets/img/Vaishnavi_Passport_Photo.JPG
description: <p align="center"> Data science profile </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

